CREATE TABLE LOGIN
(
	ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	CPF VARCHAR(11) CONSTRAINT CPF_UNICO UNIQUE (CPF) NOT NULL,
	LOGIN VARCHAR (50) CONSTRAINT LOGIN_UNICO UNIQUE (LOGIN),
	SENHA NVARCHAR (10),
	EMAIL VARCHAR (100),

);
