CREATE TABLE USUARIOS
(
	ID INT IDENTITY (1,1) PRIMARY KEY NOT NULL,
	CPF VARCHAR(11) CONSTRAINT CPF_UNICO UNIQUE (CPF) NOT NULL,
	USUARIO VARCHAR (50) CONSTRAINT USUARIO_UNICO UNIQUE (USUARIO) NOT NULL,
	SENHA NVARCHAR (10) NOT NULL,
	EMAIL VARCHAR (100) CONSTRAINT EMAIL_ASSOCIADO UNIQUE (EMAIL) NOT NULL,
	CELULAR VARCHAR (11)CONSTRAINT CEL_ASSOCIADO UNIQUE (CELULAR)
);

CREATE OR ALTER PROC INSERIR_USUARIO @CPF VARCHAR(11), @USUARIO VARCHAR(50), @SENHA VARCHAR (10), @EMAIL VARCHAR(100), @CELULAR VARCHAR(11) AS BEGIN
INSERT INTO dbo.USUARIOS (CPF, USUARIO,SENHA,EMAIL,CELULAR) VALUES (@CPF,@USUARIO,@SENHA,@EMAIL,@CELULAR)
END;


SELECT * FROM dbo.USUARIOS WHERE ID = @id;

EXEC INSERIR_USUARIO 98765432111, GalvoArte, 35487761, 'financeiro@galvoarteinox.com.br', 1432830411;